In [52]:
import pandas as pd

df = pd.read_csv("orders.csv")

In [11]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [19]:
df.iloc[10]

OrderID                  1011
CustomerName    Sophie Martin
Product                Webcam
Category          Electronics
Quantity                    1
Price                    85.0
OrderDate          2024-06-12
Shipped                   Yes
Country                France
Name: 10, dtype: object

In [ ]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [23]:
df[(df['Category'] == 'Electronics') & (df['Country'] == 'USA')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [ ]:
df[(df['Category'] == 'Electronics') | (df['Country'] == 'USA')]

In [25]:
df[df["Quantity"] != 2]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [26]:
df[df["CustomerName"].str.startswith("A")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [27]:

df[df["CustomerName"].str.endswith("a")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [30]:
df[df["Country"].isin(["USA", "Sweden"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [ ]:

df[~df["Country"].isin(["USA", "Sweden"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [33]:
df.loc[df['CustomerName'] == 'Anna Ivanova', "Product"] = "Tim"

In [34]:

df.loc[df['CustomerName'] == 'Anna Ivanova'  ]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Tim,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [ ]:
df.loc[df["Country"] == "USA", "Country"] = "United States"

In [ ]:

df.loc[df["Country"] == "United States"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,United States
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,United States
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,United States

In [ ]:
df["Country"] = df["Country"].str.upper()

In [39]:
df["Country"]

0     United States
1            Canada
2               UAE
3         Singapore
4            Mexico
5               UAE
6                UK
7       South Korea
8             Italy
9             Japan
10           France
11            India
12        Australia
13            Spain
14            China
15            Egypt
16           Poland
17    United States
18            Japan
19     Saudi Arabia
20           Canada
21           Brazil
22          Germany
23         Pakistan
24           Sweden
25           France
26        Argentina
27           Russia
28      South Korea
29            Italy
30          Morocco
31          Germany
32         Colombia
33    United States
34            Japan
35               UK
36         Portugal
37             Iran
38      South Korea
39          Ukraine
Name: Country, dtype: object

In [40]:
df = df.drop(39)

In [41]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [42]:
df = df.dropna()

In [44]:
df = df.fillna({"OrderID": 0}, inplace=True)

In [53]:
df.rename(columns={"OrderID": "Order ID"}, inplace=True)

In [54]:
df

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [55]:
df["Country"].value_counts()

Country
USA             3
South Korea     3
Japan           3
UK              2
UAE             2
Italy           2
Germany         2
France          2
Canada          2
Iran            1
Portugal        1
Colombia        1
Morocco         1
Russia          1
Argentina       1
Sweden          1
Pakistan        1
Egypt           1
Brazil          1
Saudi Arabia    1
Poland          1
China           1
Spain           1
Australia       1
India           1
Mexico          1
Singapore       1
Ukraine         1
Name: count, dtype: int64

In [57]:

df.groupby("Country")["Price"].sum()
df.sort_values("Price", ascending=False)

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [58]:
df.to_csv("cleaned_orders.csv", index=False)